using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.AI.Navigation;
using MiniMapGame.Core;
using MiniMapGame.Data;
using MiniMapGame.MapGen;

namespace MiniMapGame.Runtime
{
    /// <summary>
    /// Orchestrates map generation. Owns MapData and exposes events.
    /// After rendering roads and spawning buildings, bakes NavMesh for player navigation.
    /// </summary>
    public class MapManager : MonoBehaviour
    {
        [Header("Configuration")]
        public MapPreset activePreset;
        public int seed;

        [Header("References")]
        public MapRenderer mapRenderer;
        public BuildingSpawner buildingSpawner;

        [Header("Ground")]
        [Tooltip("If null, a ground plane is auto-generated based on preset size")]
        public GameObject groundPlane;
        public Material groundMaterial;
        public float groundYOffset = -0.01f;

        [Header("NavMesh")]
        [Tooltip("If null, NavMeshSurface is auto-added to ground")]
        public NavMeshSurface navMeshSurface;

        public MapData CurrentMap { get; private set; }

        public event Action<MapData> OnMapGenerated;
        public event Action OnMapCleared;

        private GameObject _autoGeneratedGround;

        private void Start()
        {
            if (activePreset != null)
                Generate();
        }

        public void Generate()
        {
            Generate(seed);
        }

        public void Generate(int newSeed)
        {
            seed = newSeed;
            Clear();

            var rng = new SeededRng(seed);
            float cx = activePreset.worldWidth * (0.30f + rng.Next() * 0.22f);
            float cy = activePreset.worldHeight * (0.32f + rng.Next() * 0.30f);
            var center = new Vector2(cx, cy);

            IMapGenerator generator = CreateGenerator(activePreset.generatorType);
            var (nodes, edges) = generator.Generate(rng, center, activePreset);
            var buildings = BuildingPlacer.Place(nodes, edges, rng, activePreset);
            var terrain = TerrainGenerator.Generate(rng, center, activePreset);
            var analysis = MapAnalyzer.Analyze(nodes, edges);

            CurrentMap = new MapData
            {
                nodes = nodes,
                edges = edges,
                buildings = buildings,
                terrain = terrain,
                analysis = analysis,
                center = center,
                seed = seed
            };

            // Render roads and spawn buildings first
            if (mapRenderer != null) mapRenderer.Render(CurrentMap);
            if (buildingSpawner != null) buildingSpawner.Spawn(CurrentMap);

            // Ground plane (needed for NavMesh and player raycast)
            EnsureGroundPlane();

            // Bake NavMesh after all geometry is in place
            BakeNavMesh();

            OnMapGenerated?.Invoke(CurrentMap);
        }

        public void Clear()
        {
            if (mapRenderer != null) mapRenderer.Clear();
            if (buildingSpawner != null) buildingSpawner.Clear();

            if (_autoGeneratedGround != null)
            {
                Destroy(_autoGeneratedGround);
                _autoGeneratedGround = null;
            }

            CurrentMap = null;
            OnMapCleared?.Invoke();
        }

        private void EnsureGroundPlane()
        {
            if (groundPlane != null) return;

            // Auto-generate a flat ground plane matching the map size
            _autoGeneratedGround = GameObject.CreatePrimitive(PrimitiveType.Plane);
            _autoGeneratedGround.name = "GeneratedGround";
            _autoGeneratedGround.layer = LayerMask.NameToLayer("Ground");
            _autoGeneratedGround.transform.SetParent(transform);

            // Unity Plane is 10x10 units by default at scale 1
            float scaleX = activePreset.worldWidth / 10f;
            float scaleZ = activePreset.worldHeight / 10f;
            _autoGeneratedGround.transform.localScale = new Vector3(scaleX, 1f, scaleZ);

            // Center the plane in world space (Y-inverted coordinate system)
            float centerX = activePreset.worldWidth * 0.5f;
            float centerZ = activePreset.worldHeight * 0.5f;
            _autoGeneratedGround.transform.position = new Vector3(centerX, groundYOffset, centerZ);

            if (groundMaterial != null)
            {
                _autoGeneratedGround.GetComponent<Renderer>().material = groundMaterial;
            }

            groundPlane = _autoGeneratedGround;
        }

        private void BakeNavMesh()
        {
            if (navMeshSurface == null && groundPlane != null)
            {
                navMeshSurface = groundPlane.GetComponent<NavMeshSurface>();
                if (navMeshSurface == null)
                    navMeshSurface = groundPlane.AddComponent<NavMeshSurface>();
            }

            if (navMeshSurface != null)
            {
                navMeshSurface.collectObjects = CollectObjects.All;
                navMeshSurface.BuildNavMesh();
                Debug.Log("[MapManager] NavMesh baked successfully.");
            }
        }

        private static IMapGenerator CreateGenerator(GeneratorType type)
        {
            return type switch
            {
                GeneratorType.Organic => new OrganicGenerator(),
                GeneratorType.Grid => new GridGenerator(),
                GeneratorType.Mountain => new MountainGenerator(),
                GeneratorType.Rural => new RuralGenerator(),
                _ => new OrganicGenerator()
            };
        }
    }
}
