using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.AI.Navigation;
using MiniMapGame.Core;
using MiniMapGame.Data;
using MiniMapGame.MapGen;

namespace MiniMapGame.Runtime
{
    /// <summary>
    /// Orchestrates map generation. Owns MapData and exposes events.
    /// After rendering roads and spawning buildings, bakes NavMesh for player navigation.
    /// </summary>
    public class MapManager : MonoBehaviour
    {
        [Header("Configuration")]
        public MapPreset activePreset;
        public int seed;

        [Header("References")]
        public MapRenderer mapRenderer;
        public BuildingSpawner buildingSpawner;

        [Header("Ground")]
        [Tooltip("If null, a ground plane is auto-generated based on preset size")]
        public GameObject groundPlane;
        public Material groundMaterial;
        public float groundYOffset = -0.01f;

        [Header("NavMesh")]
        [Tooltip("If null, NavMeshSurface is auto-added to ground")]
        public NavMeshSurface navMeshSurface;

        public MapData CurrentMap { get; private set; }
        public ElevationMap CurrentElevationMap { get; private set; }

        public event Action<MapData> OnMapGenerated;
        public event Action OnMapCleared;

        private GameObject _autoGeneratedGround;

        private void Start()
        {
            if (activePreset != null)
                Generate();
        }

        public void Generate()
        {
            Generate(seed);
        }

        public void Generate(int newSeed)
        {
            seed = newSeed;
            Clear();

            var rng = new SeededRng(seed);
            float cx = activePreset.worldWidth * (0.30f + rng.Next() * 0.22f);
            float cy = activePreset.worldHeight * (0.32f + rng.Next() * 0.30f);
            var center = new Vector2(cx, cy);

            IMapGenerator generator = CreateGenerator(activePreset.generatorType);
            var (nodes, edges) = generator.Generate(rng, center, activePreset);
            var terrain = TerrainGenerator.Generate(rng, center, activePreset);

            // Elevation: generate height map from terrain hills, apply to nodes
            CurrentElevationMap = new ElevationMap(terrain, activePreset);
            CurrentElevationMap.ApplyToNodes(nodes);

            var buildings = BuildingPlacer.Place(nodes, edges, rng, activePreset);
            var analysis = MapAnalyzer.Analyze(nodes, edges);

            CurrentMap = new MapData
            {
                nodes = nodes,
                edges = edges,
                buildings = buildings,
                terrain = terrain,
                analysis = analysis,
                center = center,
                seed = seed
            };

            // Bridge/tunnel detection (assigns edge.layer)
            BridgeTunnelDetector.Detect(CurrentMap, activePreset);

            // Pass elevation map to renderer
            if (mapRenderer != null)
            {
                mapRenderer.ElevMap = CurrentElevationMap;
                mapRenderer.Render(CurrentMap);
            }
            if (buildingSpawner != null) buildingSpawner.Spawn(CurrentMap);

            // Ground plane (needed for NavMesh and player raycast)
            EnsureGroundPlane();

            // Bake NavMesh after all geometry is in place
            BakeNavMesh();

            OnMapGenerated?.Invoke(CurrentMap);
        }

        public void Clear()
        {
            if (mapRenderer != null) mapRenderer.Clear();
            if (buildingSpawner != null) buildingSpawner.Clear();

            if (_autoGeneratedGround != null)
            {
                Destroy(_autoGeneratedGround);
                _autoGeneratedGround = null;
            }

            CurrentMap = null;
            OnMapCleared?.Invoke();
        }

        private const int GroundGridRes = 20;

        private void EnsureGroundPlane()
        {
            if (groundPlane != null) return;

            _autoGeneratedGround = new GameObject("GeneratedGround");
            _autoGeneratedGround.layer = LayerMask.NameToLayer("Ground");
            _autoGeneratedGround.transform.SetParent(transform);
            _autoGeneratedGround.transform.position = Vector3.up * groundYOffset;

            var mesh = GenerateGroundMesh();
            _autoGeneratedGround.AddComponent<MeshFilter>().mesh = mesh;
            var mr = _autoGeneratedGround.AddComponent<MeshRenderer>();
            if (groundMaterial != null) mr.material = groundMaterial;

            _autoGeneratedGround.AddComponent<MeshCollider>().sharedMesh = mesh;

            groundPlane = _autoGeneratedGround;
        }

        private Mesh GenerateGroundMesh()
        {
            int res = GroundGridRes;
            float w = activePreset.worldWidth;
            float h = activePreset.worldHeight;

            var verts = new Vector3[(res + 1) * (res + 1)];
            var uvs = new Vector2[verts.Length];
            var tris = new int[res * res * 6];

            for (int z = 0; z <= res; z++)
            {
                for (int x = 0; x <= res; x++)
                {
                    int idx = z * (res + 1) + x;
                    float fx = x / (float)res;
                    float fz = z / (float)res;

                    // Map coordinates for elevation sampling
                    float mapX = fx * w;
                    float mapY = (1f - fz) * h; // Y-inverted
                    float elev = CurrentElevationMap != null
                        ? CurrentElevationMap.Sample(new Vector2(mapX, mapY))
                        : 0f;

                    verts[idx] = new Vector3(fx * w, elev, fz * h);
                    uvs[idx] = new Vector2(fx, fz);
                }
            }

            int ti = 0;
            for (int z = 0; z < res; z++)
            {
                for (int x = 0; x < res; x++)
                {
                    int bl = z * (res + 1) + x;
                    int br = bl + 1;
                    int tl = bl + (res + 1);
                    int tr = tl + 1;

                    tris[ti++] = bl;
                    tris[ti++] = tl;
                    tris[ti++] = br;
                    tris[ti++] = br;
                    tris[ti++] = tl;
                    tris[ti++] = tr;
                }
            }

            var mesh = new Mesh();
            mesh.vertices = verts;
            mesh.uv = uvs;
            mesh.triangles = tris;
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        private void BakeNavMesh()
        {
            if (navMeshSurface == null && groundPlane != null)
            {
                navMeshSurface = groundPlane.GetComponent<NavMeshSurface>();
                if (navMeshSurface == null)
                    navMeshSurface = groundPlane.AddComponent<NavMeshSurface>();
            }

            if (navMeshSurface != null)
            {
                navMeshSurface.collectObjects = CollectObjects.All;
                navMeshSurface.BuildNavMesh();
                Debug.Log("[MapManager] NavMesh baked successfully.");
            }
        }

        private static IMapGenerator CreateGenerator(GeneratorType type)
        {
            return type switch
            {
                GeneratorType.Organic => new OrganicGenerator(),
                GeneratorType.Grid => new GridGenerator(),
                GeneratorType.Mountain => new MountainGenerator(),
                GeneratorType.Rural => new RuralGenerator(),
                _ => new OrganicGenerator()
            };
        }
    }
}
