using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.AI.Navigation;
using MiniMapGame.Core;
using MiniMapGame.Data;
using MiniMapGame.MapGen;

namespace MiniMapGame.Runtime
{
    /// <summary>
    /// Orchestrates map generation. Owns MapData and exposes events.
    /// After rendering roads and spawning buildings, bakes NavMesh for player navigation.
    /// </summary>
    public class MapManager : MonoBehaviour
    {
        [Header("Configuration")]
        public MapPreset activePreset;
        public int seed;

        [Header("References")]
        public MapRenderer mapRenderer;
        public BuildingSpawner buildingSpawner;
        public WaterRenderer waterRenderer;
        public DecorationSpawner decorationSpawner;

        [Header("Ground")]
        [Tooltip("If null, a ground plane is auto-generated based on preset size")]
        public GameObject groundPlane;
        public Material groundMaterial;
        public float groundYOffset = -0.01f;

        [Header("Ground Surface Compositing")]
        [Tooltip("Resolution of the ground mesh grid (vertex count per axis)")]
        public int groundGridResolution = 96;
        [Tooltip("Resolution of baked semantic mask textures")]
        public int groundMaskResolution = 1024;
        [Tooltip("Bezier curve subdivision count for road mask baking")]
        public int roadBezierSegments = 8;
        [Tooltip("Intersection radius multiplier for mask baking")]
        public float intersectionRadiusFactor = 1.5f;

        [Header("NavMesh")]
        [Tooltip("If null, NavMeshSurface is auto-added to ground")]
        public NavMeshSurface navMeshSurface;

        public MapData CurrentMap { get; private set; }
        public ElevationMap CurrentElevationMap { get; private set; }
        public GroundSemanticMaskSet CurrentMaskSet { get; private set; }

        public event Action<MapData> OnMapGenerated;
        public event Action OnMapCleared;

        private GameObject _autoGeneratedGround;
        private Material _groundMaterialInstance;

        private void Start()
        {
            if (activePreset != null)
                Generate();
        }

        public void Generate()
        {
            Generate(seed);
        }

        public void Generate(int newSeed)
        {
            seed = newSeed;
            Clear();

            var rng = new SeededRng(seed);
            float cx = activePreset.worldWidth * (0.30f + rng.Next() * 0.22f);
            float cy = activePreset.worldHeight * (0.32f + rng.Next() * 0.30f);
            var center = new Vector2(cx, cy);

            IMapGenerator generator = CreateGenerator(activePreset.generatorType);
            var (nodes, edges) = generator.Generate(rng, center, activePreset);

            // Determine coast side early (hills need this for coast-aware placement)
            int coastSide = WaterGenerator.DetermineCoastSide(rng, activePreset);

            var terrain = TerrainGenerator.Generate(rng, center, activePreset, coastSide, nodes);

            // Elevation: generate height map from terrain hills
            CurrentElevationMap = new ElevationMap(terrain, activePreset);

            // Generate water bodies (terrain-responsive: uses ElevationMap for valley following)
            terrain.waterBodies = WaterGenerator.Generate(rng, center, activePreset,
                coastSide, nodes, CurrentElevationMap);

            // Water carving: rivers create valleys, coasts create shore slopes
            WaterTerrainInteraction.ApplyWaterCarving(
                CurrentElevationMap, terrain.waterBodies, activePreset);

            // Apply elevation to nodes (after carving for final terrain shape)
            CurrentElevationMap.ApplyToNodes(nodes);

            var buildings = BuildingPlacer.Place(nodes, edges, rng, activePreset, terrain);
            var analysis = MapAnalyzer.Analyze(nodes, edges);

            CurrentMap = new MapData
            {
                nodes = nodes,
                edges = edges,
                buildings = buildings,
                terrain = terrain,
                analysis = analysis,
                center = center,
                seed = seed
            };

            // Bridge/tunnel detection (assigns edge.layer)
            BridgeTunnelDetector.Detect(CurrentMap, activePreset);

            // Bake ground semantic masks (CPU, deterministic)
            BakeGroundMasks();

            // Pass elevation map to renderer
            if (mapRenderer != null)
            {
                mapRenderer.ElevMap = CurrentElevationMap;
                mapRenderer.Render(CurrentMap);
            }
            if (buildingSpawner != null) buildingSpawner.Spawn(CurrentMap);
            if (waterRenderer != null) waterRenderer.Render(CurrentMap);

            // Decoration placement and spawning (terrain-aware)
            var decorations = DecorationPlacer.Place(
                nodes, edges, analysis, buildings, rng, activePreset,
                CurrentElevationMap, terrain);
            CurrentMap.decorations = decorations;
            if (decorationSpawner != null) decorationSpawner.Spawn(CurrentMap);

            // Ground plane (needed for NavMesh and player raycast)
            EnsureGroundPlane();

            // Bake NavMesh asynchronously to avoid blocking the main thread
            StartCoroutine(BakeNavMeshAsync());
        }

        public void Clear()
        {
            StopAllCoroutines();

            if (mapRenderer != null) mapRenderer.Clear();
            if (buildingSpawner != null) buildingSpawner.Clear();
            if (waterRenderer != null) waterRenderer.Clear();
            if (decorationSpawner != null) decorationSpawner.Clear();

            if (_autoGeneratedGround != null)
            {
                Destroy(_autoGeneratedGround);
                _autoGeneratedGround = null;
            }

            // Clean up mask textures and material instance
            if (CurrentMaskSet != null)
            {
                CurrentMaskSet.DestroyTextures();
                CurrentMaskSet = null;
            }
            if (_groundMaterialInstance != null)
            {
                Destroy(_groundMaterialInstance);
                _groundMaterialInstance = null;
            }

            CurrentMap = null;
            OnMapCleared?.Invoke();
        }

        private void EnsureGroundPlane()
        {
            if (groundPlane != null) return;

            _autoGeneratedGround = new GameObject("GeneratedGround");
            _autoGeneratedGround.layer = LayerMask.NameToLayer("Ground");
            _autoGeneratedGround.transform.SetParent(transform);
            _autoGeneratedGround.transform.position = Vector3.up * groundYOffset;

            var mesh = GenerateGroundMesh();
            _autoGeneratedGround.AddComponent<MeshFilter>().mesh = mesh;
            var mr = _autoGeneratedGround.AddComponent<MeshRenderer>();

            // Use material instance so per-map mask textures don't pollute the shared asset
            if (groundMaterial != null)
            {
                _groundMaterialInstance = new Material(groundMaterial);
                _groundMaterialInstance.name = groundMaterial.name + " (Instance)";
            }

            if (_groundMaterialInstance != null)
            {
                // Bind baked mask textures
                if (CurrentMaskSet != null)
                {
                    _groundMaterialInstance.SetTexture("_GroundHeightSlopeTex",
                        CurrentMaskSet.HeightSlopeTexture);
                    _groundMaterialInstance.SetTexture("_GroundSemanticTex",
                        CurrentMaskSet.SemanticTexture);
                }

                // Bind preset defaults for compositing strengths
                var defaults = GroundSurfacePresetDefaults.Get(activePreset.generatorType);
                _groundMaterialInstance.SetFloat("_HillshadeStrength", defaults.hillshadeStrength);
                _groundMaterialInstance.SetFloat("_ContourStrength", defaults.contourStrength);
                _groundMaterialInstance.SetFloat("_MoistureStrength", defaults.moistureStrength);
                _groundMaterialInstance.SetFloat("_RoadInfluenceStrength", defaults.roadInfluenceStrength);
                _groundMaterialInstance.SetFloat("_BuildingInfluenceStrength", defaults.buildingInfluenceStrength);
                _groundMaterialInstance.SetFloat("_NearStart", defaults.nearStart);
                _groundMaterialInstance.SetFloat("_NearEnd", defaults.nearEnd);

                mr.material = _groundMaterialInstance;
            }

            _autoGeneratedGround.AddComponent<MeshCollider>().sharedMesh = mesh;

            groundPlane = _autoGeneratedGround;
        }

        private void BakeGroundMasks()
        {
            if (CurrentMap == null || activePreset == null) return;

            var sw = System.Diagnostics.Stopwatch.StartNew();

            CurrentMaskSet = GroundSemanticMaskBaker.Bake(
                CurrentMap,
                CurrentElevationMap,
                activePreset,
                activePreset.roadProfile,
                roadBezierSegments,
                intersectionRadiusFactor,
                groundMaskResolution);

            sw.Stop();
            Debug.Log($"[MapManager] Ground masks baked ({groundMaskResolution}x{groundMaskResolution}) in {sw.ElapsedMilliseconds}ms.");
        }

        private Mesh GenerateGroundMesh()
        {
            int res = groundGridResolution;
            float w = activePreset.worldWidth;
            float h = activePreset.worldHeight;

            var verts = new Vector3[(res + 1) * (res + 1)];
            var uvs = new Vector2[verts.Length];
            var tris = new int[res * res * 6];

            for (int z = 0; z <= res; z++)
            {
                for (int x = 0; x <= res; x++)
                {
                    int idx = z * (res + 1) + x;
                    float fx = x / (float)res;
                    float fz = z / (float)res;

                    // Map coordinates for elevation sampling
                    float mapX = fx * w;
                    float mapY = (1f - fz) * h; // Y-inverted
                    float elev = CurrentElevationMap != null
                        ? CurrentElevationMap.Sample(new Vector2(mapX, mapY))
                        : 0f;

                    verts[idx] = new Vector3(fx * w, elev, fz * h);
                    uvs[idx] = new Vector2(fx, fz);
                }
            }

            int ti = 0;
            for (int z = 0; z < res; z++)
            {
                for (int x = 0; x < res; x++)
                {
                    int bl = z * (res + 1) + x;
                    int br = bl + 1;
                    int tl = bl + (res + 1);
                    int tr = tl + 1;

                    tris[ti++] = bl;
                    tris[ti++] = tl;
                    tris[ti++] = br;
                    tris[ti++] = br;
                    tris[ti++] = tl;
                    tris[ti++] = tr;
                }
            }

            var mesh = new Mesh();
            mesh.vertices = verts;
            mesh.uv = uvs;
            mesh.triangles = tris;
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        private IEnumerator BakeNavMeshAsync()
        {
            if (navMeshSurface == null && groundPlane != null)
            {
                navMeshSurface = groundPlane.GetComponent<NavMeshSurface>();
                if (navMeshSurface == null)
                    navMeshSurface = groundPlane.AddComponent<NavMeshSurface>();
            }

            if (navMeshSurface != null)
            {
                navMeshSurface.collectObjects = CollectObjects.All;

                // Yield one frame so the scene renders before the blocking bake
                yield return null;

                var sw = System.Diagnostics.Stopwatch.StartNew();
                navMeshSurface.BuildNavMesh();
                sw.Stop();
                Debug.Log($"[MapManager] NavMesh baked successfully ({sw.ElapsedMilliseconds}ms).");
            }

            OnMapGenerated?.Invoke(CurrentMap);
        }

        private static IMapGenerator CreateGenerator(GeneratorType type)
        {
            return type switch
            {
                GeneratorType.Organic => new OrganicGenerator(),
                GeneratorType.Grid => new GridGenerator(),
                GeneratorType.Mountain => new MountainGenerator(),
                GeneratorType.Rural => new RuralGenerator(),
                _ => new OrganicGenerator()
            };
        }
    }
}
